name: build-only
on:
  push:
    branches:
      - '*'
jobs:
  build-only:
    name: build-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - uses: arduino/setup-protoc@v1
      - run: sudo apt-get install make
      - run: make get-protos
